version: "3.10"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5433"
  web:
    build: .
    container_name: adminka
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: /entrypoint.sh
  bot:
    container_name: bot
    command: bash -c "python manage.py bot"
    env_file:
      - ./.env
    depends_on:
      - db
      - web
