# Generated by Django 4.1.2 on 2022-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior')], default='1')),
                ('message', models.TextField()),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deep_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_blocked_bot',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='counter',
            field=models.PositiveIntegerField(default=0, max_length=555),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
