# Generated by Django 4.1.2 on 2022-10-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_message_delete_config_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
