# Generated by Django 4.1.2 on 2022-10-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_alter_message_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.PositiveIntegerField(choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior')], default='1'),
        ),
    ]
