# Generated by Django 4.1.2 on 2022-10-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_alter_message_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.PositiveIntegerField(choices=[], default=1),
        ),
    ]
