# Generated by Django 4.1.2 on 2022-11-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_message_probability_alter_message_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.profile')),
            ],
        ),
    ]
