# Generated by Django 4.1.2 on 2022-11-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0009_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniq',
            name='mes',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
