# Generated by Django 4.1.2 on 2022-11-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_alter_uniq_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniq',
            name='user',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
