# Generated by Django 4.1.2 on 2022-11-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_alter_uniq_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.profile'),
        ),
    ]
